name: deploy via ssh

on:
    push:
        branches: 
            [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps: 
        - uses: actions/checkout@v4

        - name: set up go
          uses: actions/setup-go@v5
          with: 
            go-version: 1.24.2
        
        - name: build binary
          run: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build -ldflags="-s -w" -o myapp

        - name: copy binary ro VPS
          uses: appleboy/scp-action@v0.1.7
          with: 
            host: ${{ secrets.VPS_HOST }}
            port: ${{ secrets.VPS_PORT }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.SSH_KEY }}
            source: "myapp"
            target: "/opt/guide-backend/"

        - name: restart service
          uses: appleboy/ssh-action@v1.0.0
          env: 
            HOST_KEY_CHECKING: false
          with: 
            host: ${{ secrets.VPS_HOST }}
            port: ${{ secrets.VPS_PORT }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              sudo systemctl stop guide-backend || true
              sudo mv /opt/guide-backend/myapp /opt/guide-backend/bin && \
              sudo chmod +x /opt/guide-backend/guide-backend
              sudo systemctl daemon-reload
              sudo systemctl start guide-backend

            