name: deploy via ssh

on:
    push:
        branches: 
            [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps: 
        - uses: actions/checkout@v4

        - name: set up go
          uses: actions/setup-go@v5
          with: 
            go-version: 1.24.2
        
        - name: build binary
          run: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build -ldflags="-s -w" -o myapp

        - name: upload binary to remote
          run: |
            cat myapp | \
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} \
              ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
              "cat > /tmp/guide-backend.new && \
              sudo mv /tmp/guide-backend.new /opt/guide-backend/guide-backend && \
              sudo chmod +x /opt/guide-backend/guide-backend && \
              sudo systemctl daemon-reload && \
              sudo systemctl start guide-backend"

        - name: Deploy via SSH
          uses: appleboy/ssh-action@v1.0.0
          env: 
            HOST_KEY_CHECKING: false
          with: 
            host: ${{ secrets.VPS_HOST }}
            port: ${{ secrets.VPS_PORT }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              set -e
              sudo systemctl stop guide-backend || true
              cat > /tmp/guide-backend.new && \
              sudo mv /tmp/guide-backend.new /opt/guide-backend/guide-backend && \
              sudo chmod +x /opt/guide-backend/guide-backend
              sudo systemctl daemon-reload
              sudo systemctl start guide-backend

            