name: deploy via ssh

on:
    push:
        branches: 
            [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps: 
        - uses: actions/checkout@v4

        - name: set up go
          uses: actions/setup-go@v5
          with: 
            go-version: 1.24.2
        
        - name: build binary
          run: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build -ldflags="-s -w" -o myapp ./cmd/guide-backend

        - name: Deploy via SSH
          uses: appleboy/ssh-action@v1.0.0
          with: 
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.VPS_PORT }}
            script: |
              set -e
              sudo systemctl stop guide-bakend || true

              rsync -avz --progress "$GIHUB_WORKSPACE/myapp" ${{ secrets.VPS_USER}}@${{ secrets.VPS_HOST }}:${{ secrets.APP_DIR }}/myapp.new
              
              ssh ${{ secrets.VPS_USER }}:${{ secrets.VPS_HOST }} "mv ${{secrets.APP_DIR }}/myapp.new ${{ secrets.APP_DIR }}/guide-backend && chmod +x ${{ secrets.APP_DIR }}/guide-backend"
              
              sudo systemctl daemon-reload
              sudo systemctl start guide-backend

            